### PR TITLE
Update MkRules.local.in

### PR DESCRIPTION
**Pull request by aadler**
Allow for external BLAS like OPEN_BLAS on Windows. Access existing variable in MkRules.dist

### CODE REVIEW

**Comment by jeroen** [comment]
This doesn't change anything? How would you use this?

**Comment by aadler** [comment]
I pass
```bash
USE_ATLAS = YES
ATLAS_PATH = C:/R/OPB
```
in `MkRules.local.in` which overwrites the existing `ATLAS_PATH` in `Mkrules.dist` and then I use a personal `blas.diff` to change src/extras/blas/Makerules.win to pass the proper library name as I have done for R 2+/3+ for years. The blas diff looks like
```bash
--- a/src/extra/blas/Makefile.win
+++ b/src/extra/blas/Makefile.win
@@ -12,7 +12,7 @@
 ../../../$(BINDIR)/Rblas.dll: blas00.o ../../gnuwin32/dllversion.o
 	@$(ECHO) -------- Building $@ --------
 	$(DLL) -shared $(DLLFLAGS) -o $@ $^ Rblas.def \
-	   -L../../../$(IMPDIR) -lR  -L"$(ATLAS_PATH)" -lf77blas -latlas
+	   -L../../../$(IMPDIR) -lR  -L"$(ATLAS_PATH)" -lopenblas
 else
 ../../../$(BINDIR)/Rblas.dll: blas.o cmplxblas.o ../../gnuwin32/dllversion.o
 	@$(ECHO) -------- Building $@ --------
```
So in `PKGBUILD` I have:
```bash
# Default source is R-devel (override via $rsource_url)
source=(R-source.tar.gz::"${rsource_url:-https://cran.r-project.org/src/base-prerelease/R-devel.tar.gz}"
    https://curl.haxx.se/ca/cacert.pem
    MkRules.local.in
    shortcut.diff
    create-tcltk-bundle.sh
	blas.diff)

# Automatic untar fails due to embedded symlinks
noextract=(R-source.tar.gz)

sha256sums=('SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
            'SKIP'
	   'SKIP')
[SNIP]
  # Add your patches here
  patch -Np1 -i "${srcdir}/shortcut.diff"
  patch -Np1 -i "${srcdir}/blas.diff"
}
```

And this works.

**Comment by jeroen** [comment]
OK but if you are locally changing `ATLAS_PATH` anyway to work with your local patches, I don't understand the purpose of this PR.

**Comment by aadler** [comment]
I was thinking that it would inform people that the variable can be addressed from the `Mkrules.local.in`, but after thinking about it, since it isn't standard, perhaps it makes sense to leave it out, knowing that `Mkrules.local.in` can override any "named variable" in `Mkrules.dist` as needed. I leave it up to you to close should you wish. Thanks.

**Pull request closed without merging**
