### PR TITLE
Tweaks to build with Rtools42

### PR DESCRIPTION
**Pull request by yutannihilation**
I needed to some tweak to make the build success. Not sure about the current status, but I think this repository needs some clarification about Rtools42 at least.

c.f. https://developer.r-project.org/WindowsBuilds/winutf8/ucrt3/howto.html

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks for your suggestion. This repository is designed around the rtools40 system, with external libraries being provided via the [rtools-packges](https://github.com/r-windows/rtools-packages) repository. It is currently still used to build dailies for 4.1 (r-patched) that rely on this version.

Sadly r-core has decided that to abandon our build infrastructure for rtools42 and go back to building R manually by an r-core member, without CI. The new windows maintainer has his own methods and does not want to collaborate in any way, so I think we will discontinue this repository after the release of R-4.2.

**Comment by yutannihilation** [comment]
Thanks for the details. That's really bad... Would you mind if I post about this to R-devel mailing list to discuss the build infrastructure? As a user, the current situation is very confusing and I want to improve.

**Comment by llrs** [comment]
This was somewhat already discussed on the r-devel mailing list back on August (see this thread about the different [rtools systems](https://stat.ethz.ch/pipermail/r-devel/2021-August/081020.html)) not sure of any other development. Perhaps you @yutannihilation might be already aware of it but it might be a good thread to link if you brought back this on the mailing list. However the [CRAN team is on holidays and maintenance mode](https://cran.r-project.org/):

> CRAN submission is offline from Dec 21, 2021 to Jan 3, 2022 (CRAN team vacation and maintenance work). 

So I would probably wait a couple of weeks after they come back (just to let them reduce the pressure of the new submission after the holidays)

**Comment by yutannihilation** [comment]
Ah, thanks. Yes, I actually saw the post (and [another conversation](https://github.com/r-spatial/stars/issues/453#issuecomment-915509105) as well). But, since Jeroen and other R core members didn't continue the discussion on the mailing list, I thought they would have a talk on this in some other place. Then, the recent [blog post](https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/index.html) officially declared to switch the Rtools, with mentioning Jeroen, so I hoped they reached some agreement that would let the upgrade land softly.

Sorry, I should have joined the discussion at that time. If it's not too late, I'd like to post.

> However the [CRAN team is on holidays and maintenance mode](https://cran.r-project.org/):

If I understand correctly, who I need to catch the attention of is the R-core, not the CRAN team. But, I'll hold for a week or so, thanks for your advice. Wish you a happy holiday, too :)

**Comment by jeroen** [comment]
There was no soft landing. Following up on the post, several r-core members personally attacked me, others apologised, but in the end it was decided that they will support whatever Tomas Kalibera wants, and they don't want any public discussion or collaboration.

**Comment by yutannihilation** [comment]
Really sorry to hear that. I have no words to say...

Considering that consequence, I now feel there's little hope to improve the situation if I post anything in the mailing list. Though I'm almost powerless here, if there's anything I can help you, please let me know. Your contribution to R is huge, you should be more rewarded.

**Pull request closed without merging**
